In [1]:
import torch,torchvision
from torchvision import datasets
from torchvision.transforms import ToTensor

import matplotlib.pyplot as plt

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [3]:
!nvidia-smi

Tue Sep 22 00:30:35 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 610.62                 KMD Version: 610.62        CUDA UMD Version: 13.3     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4060 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   53C    P8              1W /  125W |      41MiB /   8188MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [4]:
from torchvision import transforms

transformed_shvn_train = transforms.Compose([

    transforms.RandomRotation(degrees=15),
    transforms.RandomAffine(degrees=0, translate=(0.1, 0.1)),

    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2),

    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
])

In [5]:
transformed_shvn_test = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
])

In [6]:
transformed_fmnist_train = transforms.Compose([
    transforms.Resize((32, 32)),
    transforms.RandomHorizontalFlip(p = 0.5),
    transforms.RandomAffine(degrees = 10, translate=(0.1, 0.1)),

    transforms.Grayscale(num_output_channels=3),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])

])

transformed_fmnist_test = transforms.Compose([
    transforms.Resize((32, 32)),
    transforms.Grayscale(num_output_channels=3),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
])

In [7]:
transformed_cifar_train = transforms.Compose([
    transforms.RandomCrop(32, padding=4),
    transforms.RandomHorizontalFlip(p = 0.5),
    transforms.ColorJitter(brightness=0.2, contrast=0.2),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
])

transformed_cifar_test = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
])

In [8]:
cifar_data_train = datasets.CIFAR10(
    root='data/CIFAR10', 
    train=True, 
    download=True,
    transform=transformed_cifar_train
)

cifar_data_test = datasets.CIFAR10(
    root='data/CIFAR10',
    train=False,
    download=True,
    transform=transformed_cifar_test
)

Files already downloaded and verified


c:\Users\JAY\AppData\Local\Programs\Python\Python312\Lib\site-packages\torchvision\datasets\cifar.py:83: VisibleDeprecationWarning: dtype(): align should be passed as Python or NumPy boolean but got `align=0`. Did you mean to pass a tuple to create a subarray type? (Deprecated NumPy 2.4)
  entry = pickle.load(f, encoding="latin1")


Files already downloaded and verified


In [9]:
train_data_FMNIST = datasets.FashionMNIST(
    root="data",
    train = True,
    download = True,
    transform= ToTensor(),
    target_transform= None
)

test_data_FMNIST = datasets.FashionMNIST(
    root= "data",
    train = False,
    download=True,
    transform=ToTensor()

)

In [10]:
svhn_data_train = datasets.SVHN(
    root='./data/SVHN/train', 
    split='train', 
    download=True,
    transform=transformed_shvn_train
)

svhn_data_test = datasets.SVHN(
    root='./data/SVHN/test',
    split='test',
    download=True,
    transform=transformed_shvn_test
)

Using downloaded and verified file: ./data/SVHN/train\train_32x32.mat
Using downloaded and verified file: ./data/SVHN/test\test_32x32.mat


In [11]:
img,label = svhn_data_train[0]

In [12]:
print(img)
print(label)

tensor([[[-0.9137, -0.6941, -0.4745,  ..., -0.2863, -1.0000, -1.0000],
         [-0.9216, -0.6784, -0.4588,  ..., -0.3333, -1.0000, -1.0000],
         [-0.9059, -0.7882, -0.4980,  ..., -0.4353, -1.0000, -1.0000],
         ...,
         [-0.3412, -0.3569, -0.5137,  ..., -0.1686, -1.0000, -1.0000],
         [-0.3412, -0.3725, -0.3490,  ..., -0.1451, -1.0000, -1.0000],
         [-0.3176, -0.3176, -0.3490,  ..., -0.1686, -1.0000, -1.0000]],

        [[-0.8902, -0.6627, -0.4980,  ..., -0.3725, -1.0000, -1.0000],
         [-0.8667, -0.7333, -0.5216,  ..., -0.3725, -1.0000, -1.0000],
         [-0.8902, -0.7647, -0.5137,  ..., -0.4588, -1.0000, -1.0000],
         ...,
         [-0.3647, -0.3882, -0.5059,  ..., -0.1529, -1.0000, -1.0000],
         [-0.4039, -0.3490, -0.3961,  ..., -0.1608, -1.0000, -1.0000],
         [-0.3647, -0.3647, -0.3725,  ..., -0.1451, -1.0000, -1.0000]],

        [[-0.8745, -0.6627, -0.5922,  ..., -0.5529, -1.0000, -1.0000],
         [-0.8980, -0.6549, -0.5529,  ..., -0

In [13]:
class_names = train_data_FMNIST.classes
class_names

['T-shirt/top',
 'Trouser',
 'Pullover',
 'Dress',
 'Coat',
 'Sandal',
 'Shirt',
 'Sneaker',
 'Bag',
 'Ankle boot']

In [14]:
train_data_mnist = datasets.MNIST(
    root="data",
    train = True,
    download = True,
    transform= ToTensor(),
    target_transform= None
)

test_data_mnist= datasets.MNIST(
    root= "data",
    train = False,
    download=True,
    transform=ToTensor()

)

In [15]:
from torch.utils.data import ConcatDataset, Dataset

class DataWrapper(Dataset):

    def __init__(self , original_dataset,domain_id):

        self.original_dataset = original_dataset
        self.domain_id = domain_id

    def __len__(self):

        return len(self.original_dataset)

    def __getitem__(self, idx):

        img, label = self.original_dataset[idx]
        return img, label, self.domain_id
    

In [16]:
mnist_train_wrapped = DataWrapper(train_data_mnist, domain_id=0)
svhn_train_wrapped = DataWrapper(svhn_data_train, domain_id=1)
fmnist_train_wrapped = DataWrapper(train_data_FMNIST, domain_id=2)
cifar_train_wrapped = DataWrapper(cifar_data_train, domain_id=3)

In [17]:
mnist_test_wrapped = DataWrapper(test_data_mnist, domain_id=0)
svhn_test_wrapped = DataWrapper(svhn_data_test, domain_id=1)
fmnist_test_wrapped = DataWrapper(test_data_FMNIST, domain_id=2)
cifar_test_wrapped = DataWrapper(cifar_data_test, domain_id=3)

In [18]:
unified_train_dataset = ConcatDataset([
    mnist_train_wrapped, 
    svhn_train_wrapped, 
    fmnist_train_wrapped, 
    cifar_train_wrapped
])

unified_test_dataset = ConcatDataset([
    mnist_test_wrapped, 
    svhn_test_wrapped, 
    fmnist_test_wrapped, 
    cifar_test_wrapped
])

In [19]:
from torch import nn

In [20]:
# Made the baseline mode to which our route router will be compared to :

class baseLineModel(nn.Module):

    def __init__(self):
        super().__init__()

        self.block1 = nn.Sequential(
            nn.Conv2d(
                in_channels=3,
                out_channels=64,
                stride=1,
                kernel_size=3,
                padding=1
            ),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2)
        )

        self.block2 = nn.Sequential(
            nn.Conv2d(
                in_channels=64,
                out_channels=128,
                stride=1,
                kernel_size=3,
                padding=1
            ),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2)
        )

        self.block3 = nn.Sequential(
            nn.Conv2d(
                in_channels=128,
                out_channels=256,
                stride=1,
                kernel_size=3,
                padding=1
            ),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2)
        )

        self.block4 = nn.Sequential(
            nn.Conv2d(
                in_channels=256,
                out_channels=512,
                stride=1,
                kernel_size=3,
                padding=1
            ),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2)
        )

        self.Gap = nn.AdaptiveAvgPool2d((1, 1))

        self.domain_head = nn.Linear(
            in_features=512,
            out_features=4
        )

        self.class_head = nn.Linear(
            in_features=512,
            out_features=10
        )

    def forward(self, x):

        x = self.block1(x)
        x = self.block2(x)
        x = self.block3(x)
        x = self.block4(x)

        x = self.Gap(x)

        x = torch.flatten(x, 1)

        domain_output = self.domain_head(x)
        class_output = self.class_head(x)

        return domain_output, class_output


In [21]:
model_base = baseLineModel().to(device) 

In [22]:
test_input = torch.randn(64, 3, 32, 32).to(device)
test_domain_output, test_class_output = model_base(test_input)
print("Domain output shape:", test_domain_output.shape)
print("Class output shape:", test_class_output.shape)

Domain output shape: torch.Size([64, 4])
Class output shape: torch.Size([64, 10])


In [23]:
test_domain_output[0]

tensor([-0.0939,  0.0557,  0.0818,  0.0922], device='cuda:0',
       grad_fn=<SelectBackward0>)

In [24]:
test_class_output[0]

tensor([-0.0348, -0.1088,  0.0366, -0.0451, -0.0734, -0.0320,  0.1237,  0.0444,
         0.0596,  0.0221], device='cuda:0', grad_fn=<SelectBackward0>)

In [25]:
import os

unified_train_loader = torch.utils.data.DataLoader(
    unified_train_dataset,
    batch_size=64,
    shuffle=True,
    num_workers= os.cpu_count()
)

unified_test_loader = torch.utils.data.DataLoader(
    unified_test_dataset,   
    shuffle=False,
    batch_size=64,
    num_workers= os.cpu_count()
)

In [26]:
def train_baseline(model : nn.Module,
                   loss_fn_domain : nn.Module,
                   optimizer : torch.optim.Optimizer,
                   data_loader : torch.utils.data.DataLoader,
                   device : torch.device,
                   loss_fn_class : nn.Module,
                   epochs : int = 10):

    for epoch in range(epochs):

        model.train()

        train_loss = 0.0

        for images,domain,classses in data_loader :

            images = images.to(device)
            domain = domain.to(device)
            classses = classses.to(device)

            y = model(images)

            loss_domain = loss_fn_domain(y[0],domain)

            loss_class = loss_fn_class(y[1],classses)

            total_loss = loss_domain + loss_class

            train_loss += total_loss.item()

            optimizer.zero_grad()

            total_loss.backward()

            optimizer.step()

        train_loss /= len(data_loader)

        if epoch % 5 == 0 :
                print(f"Epoch [{epoch+1}/{epochs}], Loss: {train_loss:.4f}")


In [27]:
def test_baseline(model : nn.Module,
                  loss_fn_domain : nn.Module,
                  loss_fn_class : nn.Module,
                  data_loader : torch.utils.data.DataLoader,
                  device : torch.device):

    model.eval()
    with torch.inference_mode():

        test_loss = 0.0

        for images,domain,classses in data_loader :

            images = images.to(device)
            domain = domain.to(device)
            classses = classses.to(device)

            y = model(images)

            loss_domain = loss_fn_domain(y[0],domain)

            loss_class = loss_fn_class(y[1],classses)

            total_loss = loss_domain + loss_class

            test_loss += total_loss.item()

        test_loss /= len(data_loader)

        print(f"Test Loss: {test_loss:.4f}")
        

In [28]:
loss_fn_domain = nn.CrossEntropyLoss(label_smoothing=0.1)
loss_fn_class = nn.CrossEntropyLoss(label_smoothing=0.1)

optimizer = torch.optim.AdamW(model_base.parameters(), lr=3e-4)

In [ ]:
# train_baseline(
#     model=model_base,
#     loss_fn_domain=loss_fn_domain,
#     optimizer=optimizer,
#     data_loader=unified_train_loader,
#     device=device,
#     loss_fn_class=loss_fn_class,
#     epochs=1
# )

In [29]:
# Made the experts model which will be used the by the model which are connected by routes

class experts(nn.Module):

    def __init__(self):
        super().__init__()

        self.block1 = nn.Sequential(
            nn.Conv2d(
                in_channels=3,
                out_channels=32,
                stride=1,
                kernel_size=3,
                padding=1
            ),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2)
        )

        self.block2 = nn.Sequential(
            nn.Conv2d(
                in_channels=32,
                out_channels=64,
                stride=1,
                kernel_size=3,
                padding=1
            ),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2)
        )

        self.block3 = nn.Sequential(
            nn.Conv2d(
                in_channels=64,
                out_channels=128,
                stride=1,
                kernel_size=3,
                padding=1
            ),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2)
        )

        self.block4 = nn.Sequential(
            nn.Conv2d(
                in_channels=128,
                out_channels=256,
                stride=1,
                kernel_size=3,
                padding=1
            ),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2)
        )

        self.Gap = nn.AdaptiveAvgPool2d((1, 1))

        self.class_head = nn.Linear(
            in_features=256,
            out_features=10
        )

    def forward(self, x):

        x = self.block1(x)
        x = self.block2(x)
        x = self.block3(x)
        x = self.block4(x)

        x = self.Gap(x)

        x = torch.flatten(x, 1)
        class_output = self.class_head(x)

        return  class_output


In [30]:
model_fmnist = experts().to(device)
model_mnist = experts().to(device)
model_cifar = experts().to(device)
model_svhn = experts().to(device)